export default {
    SPLASH: 'Splash',
    LOGIN: 'Login',
    REGISTER: 'Register',
    MAIN_TABS: 'MainTabs',
    HOME: 'Home',
    PROFILE: 'Profile',
    SERVICE_HOME: 'ServiceHome',
    SERVICE_LISTING: 'ServiceListing',
    CHAT: 'Chat',
    CHAT_DETAIL: 'ChatDetail',
    USER_LIST: 'UserList',
    BOOKING_CONFIRMATION: 'BookingConfirmation',
    REELS: 'Reels',
    ONBOARD: 'ONBOARD',
    PAYMENT: 'PAYMENT',
} as const;
